collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.3148936
color:
  saturation: 1
  brandStrength: 0
  lightness: 0.5574468
  brandColors:
    - '#FFFFE9'
    - '#BA88C5'
    - '#21161C'
    - '#823F37'
    - '#5DCAE9'
  rhythmicContrast: 1
layout_spectrum: 0.9702128
name: Who We Are
